name=input("name")
age=input("age")
college=input("college")
print("enter the name",name,"age",age,"college",college,)
nath=input("math")
physics=input("physics")
chemistry=input("chemistry")
biology=input("biology")
english=input("english")
math=float("math")
physics=float("physics")
chemistry=float("chemistry")
biology=float("biology")
english=float("english")
sum=math+physics+chemistry+biology+english
print("total mark is the sum of your mark %.2f", sum)
